<script>
    function showTroco() {
        var opt = document.getElementById("Troco");
        if (opt.className == "d-none") {
            opt.className = "d-block form-group pt-4"
        } else {
            opt.className = "d-none"
        }
    }


    function VerifyTroco() {
        var debit = document.getElementById("debit")
        var credit = document.getElementById("credit")
        var btnSubmit = document.getElementById("btnSubmit")
        var totPedido = document.getElementById("tot_pagar").value
        var troco = document.getElementById("troco").value
        var span = document.getElementById("valueIncorrect")

        if (debit.checked == false && credit.checked == false) {
            if (troco < totPedido) {
                btnSubmit.className = "d-none"
                span.className = "d-block text-danger text-center"
                span.innerHTML = "Valor incorreto, menor que o valor total"
            } else {
                document.getElementById("btnPosition").className = "d-flex justify-content-center"
                btnSubmit.className = "d-block btn btn-dark"
                span.className = "d-none"
                span.innerHTML = ""
            }
        }
    }

    function checkRadio() {
        var debit = document.getElementById("debit")
        var credit = document.getElementById("credit")
        var btnSubmit = document.getElementById("btnSubmit")

        if (debit.checked == true || credit.checked == true) {
            document.getElementById("btnPosition").className = "d-flex justify-content-center"
            btnSubmit.className = "d-block btn btn-dark"
            span.className = "d-none"
            span.innerHTML = ""
        }
    }

    $(document).on("keydown", "form", function(event) {
        return event.key != "Enter";
    });
</script>


<section id="listaProdutos" class="my-5">
    <div class="container p-4">
        <div class="row bg-white rounded">

            <div class="col-12 col-md-6 p-4 text-center border">

                <h3>Endereço de entrega</h3>
                <hr>
                <table class="table">
                    <tr>
                        <td class="border-right">Nome </td>
                        <td><?= $_POST['cli_name'] ?></td>
                    </tr>

                    <?php

                    $taxa_entrega = 0;
                    $cidade = "";
                    switch ($_POST['cli_city']) {
                        case 1:
                            $taxa_entrega = 3.50;
                            $cidade = "Salto";
                            break;

                        case 2:
                            $taxa_entrega = 5.50;
                            $cidade = "Itu";
                            break;

                        case 3:
                            $taxa_entrega = 8.50;
                            $cidade = "Indaiatuba";
                            break;
                    }

                    ?>
                    <tr>
                        <td class="border-right" colspan="2">Rua <?= $_POST['cli_street'] ?>, nº <?= $_POST['cli_n_house'] ?></td>
                    </tr>
                    <tr>
                        <td class="border-right">Bairro </td>
                        <td><?= $_POST['cli_district'] ?></td>
                    </tr>
                    <tr>
                        <td class="border-right">Cidade </td>
                        <td><?= $cidade ?></td>
                    </tr>
                    <?php if ($_POST['cli_obs'] != "") {
                        $obs = $_POST['cli_obs']; ?>
                        <tr>
                            <td>Observação: </td>
                            <td><?= $_POST['cli_obs'] ?></td>
                        </tr>
                    <?php } else {
                        $obs = "Nenhuma observação!" ?>
                        <tr>
                            <td colspan="2">Nenhuma observação!</td>
                        </tr>
                    <?php } ?>
                </table>
            </div>
            <div class="col-12 col-md-6 p-4 text-center border">

                <h3>Dados do pedido</h3>
                <table class="table">

                    <thead>
                        <td>
                            <h5>Descrição</h5>
                        </td>
                        <td>
                            <h5>Valor</h5>
                        </td>
                    </thead>
                    <tbody>
                        <?php
                        $confid = $this->view->confid;
                        $last = $confid->getLastId()['id_pedido'];

                        function numPedi($n)
                        {
                            return $n + 1;
                        }

                        $nPedido =  numPedi((int)$last);

                        $valor_tot = 0;
                        date_default_timezone_set('America/Sao_Paulo');
                        $dataLocal = date('d/m/Y H:i:s', time());
                        $num = "+5511996271186";
                        $url = "https://wa.me/" . $num . "?text=*Pedido:%20nº%20" . $nPedido . "*%0A*Data*%20:" . $dataLocal . "%20%20%0A%0A*Produto(s)*:%0A";

                        foreach ($_POST as $indice => $value) {

                            if ($value == "") {
                                continue;
                            }
                            if ($indice == "cli_name" || $indice == "cli_city" || $indice == "cli_street" || $indice == "cli_n_house" || $indice == "cli_district") {
                                continue;
                            }
                            $id_prod = str_replace('prod_', '', $indice);

                            $produto = $confid->getInfoProd($id_prod);

                            $this->view->produtos = $produto;
                            foreach ($this->view->produtos as $indice => $value) { ?>
                                <tr>
                                    <td><?= $value['prod_title'] ?></td>
                                    <?php $value_prod = number_format($value['prod_value'], 2, ',', '.');  ?>

                                    <td><?= $value_prod ?></td>

                                    <?php $url .= $value['prod_title'] . "%20-%20R$%20" . $value_prod . "%0A" ?>
                                </tr>
                                <?php
                                $valor_tot += $value['prod_value'];
                                ?>
                                <input type='hidden' name='vl_prod' id='vl_prod' value="<?= $value['prod_value'] ?>">

                        <?php  }
                        } ?>
                    </tbody>
                </table>
                <?php
                $url .= "%0A*Nome:*%0A" . $_POST['cli_name'] . "%20%0A%0A*Endereço:*%0A" . $_POST['cli_street'] . ",%20nº%20" . $_POST['cli_n_house'] . ",%20" . $_POST['cli_district'] . ",%20" . $cidade . "%0Aobs:%20" . $obs . "%0A";
                ?>
                <div class="rounded text-dark p-4 border">
                    <form action="/envia_pedido" method="POST" onkeydown="return event.key != 'Enter';">

                        <p><strong>Valor carrinho: R$ <?= number_format($valor_tot, 2, ',', '.') ?></strong></p>
                        <input type="hidden" name="carrinho" value="<?= $valor_tot ?>">

                        <?php $vl_entrega = number_format($taxa_entrega, 2, ',', '.'); ?>
                        <p><strong>Taxa de entrega: R$ <?= $vl_entrega ?></p>
                        <input type='hidden' name='entrega' value='<?= $taxa_entrega ?>' id='tx_entrega'>

                        <div class="d-flex justify-content-around">
                            <div class="form-group">
                                <label class="border-right">
                                    Crédito
                                    <input type="radio" onclick="checkRadio()" name="methodPayment" value="credito" id="credit" class="form-control">
                                </label>

                                <label class="border-right">
                                    Débito
                                    <input type="radio" onclick="checkRadio()" name="methodPayment" value="debito" id="debit" class="form-control">
                                </label>
                                <label>
                                    dinheiro
                                    <input type="checkbox" name="money" value="" class="form-control" onclick="showTroco()" onkeypress="doNothing()">
                                </label>
                            </div>
                            <div class="d-none" id="Troco">
                                <div class="input-group">
                                    <div class="input-group-preppend">
                                        <label for="troco" class="btn btn-dark">R$</label>
                                    </div>

                                    <input type="number" name="troco" id="troco" onblur="VerifyTroco()" placeholder="Dinheiro" class="form-control">
                                </div>
                            </div>
                        </div>
                        <hr>
                        <?php
                        $troco = 0;
                        $tot_pagar =  $valor_tot + $taxa_entrega;
                        ?>

                        <h6><strong>Total a pagar: R$ <?= number_format($tot_pagar, 2, ',', '.') ?></strong></h6>
                        <input type="hidden" name="tot_pagar" id="tot_pagar" value="<?= $tot_pagar ?>">
                        <span id="errorMsg" class="text-center text-danger"></span>


                        <input type="hidden" name="url" value="<?= $url ?>">
                        <?php
                        if ($valor_tot < 1) {
                            echo "<h4 class='text-danger text-center'>Carrinho vazio!</h4>";
                        } else {
                        ?>
                            <div id="btnPosition" class="">
                                <button type="submit" class="d-none" id="btnSubmit">Finalizar Pedido</button>
                            </div>
                        <?php
                        }
                        ?>
                        <span id="valueIncorrect" class="d-none"></span>
                    </form>
                </div>

            </div>
        </div>
    </div>

</section>